// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-oxolEYjJFNix5_rX9fFd8Tzt-SvTr8w',
    appId: '1:338091236827:web:c8c8ad377b86bb74629bfe',
    messagingSenderId: '338091236827',
    projectId: 'chatting-tutorial-f2e21',
    authDomain: 'chatting-tutorial-f2e21.firebaseapp.com',
    storageBucket: 'chatting-tutorial-f2e21.appspot.com',
    measurementId: 'G-VH8CEY69T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUfYhSCPb7CzGwYtle1PhYTHoICuzHavo',
    appId: '1:338091236827:android:e6303e17dcc480e2629bfe',
    messagingSenderId: '338091236827',
    projectId: 'chatting-tutorial-f2e21',
    storageBucket: 'chatting-tutorial-f2e21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSBOO6F8SLosdAdY-1BxUcQRiseYPoOsc',
    appId: '1:338091236827:ios:4b4dfea2635f7ad9629bfe',
    messagingSenderId: '338091236827',
    projectId: 'chatting-tutorial-f2e21',
    storageBucket: 'chatting-tutorial-f2e21.appspot.com',
    iosClientId: '338091236827-ct4brdhg7q1b3m6gcr4uura3losf4sjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSBOO6F8SLosdAdY-1BxUcQRiseYPoOsc',
    appId: '1:338091236827:ios:c0a18541e389b30d629bfe',
    messagingSenderId: '338091236827',
    projectId: 'chatting-tutorial-f2e21',
    storageBucket: 'chatting-tutorial-f2e21.appspot.com',
    iosClientId: '338091236827-snka56k9ev0c7b6djcuof8frjd7uoe3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingTutorial.RunnerTests',
  );
}
